version: '3.8'

services:

    mongodb:
      image: mongodb/mongodb-community-server:latest
      container_name: mongodb
      restart: unless-stopped
      ports:
        - "27017:27017"  # Expose MongoDB on the host machine's port 27017
      volumes:
        - mongodb_data:/data/db  # Persist MongoDB data across container restarts

    backend:
      image: node:14-alpine
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
      - ./:/usr/src/api
      expose:
        - "5000"
      ports:
        - "5000:5000"
      depends_on:
        - mongodb
      command: npm run dev

volumes:
  mongodb_data:
    driver: local

